hcoles/pitest

- pitest-maven/pom.xml
- pitest-maven/src/main/java/org/pitest/maven/PitMojo.java
- pom.xml
I would like the have the 'skipTests' flag as well.
Here is my PR ;)
Cheers Lars
> added skipTests flag support

- pitest/src/main/java/org/pitest/coverage/export/DefaultCoverageExporter.java
This should fix the invalid xml problem.
> Fixed #174 invalid linecoverage.xml with static initializers

- pitest/src/main/java/org/pitest/mutationtest/incremental/FileWriterFactory.java
- pitest/src/test/java/org/pitest/mutationtest/incremental/FileWriterFactoryTest.java
- pom.xml
I was trying to record history to a folder that was not yet there.
With this fix all went green!
> When wrinting a history file, should create any directories needed

- pom.xml
Adds Rahul Gopinath to contributor list in pom.xml
> Adds Rahul Gopinath to contributor list in pom.xml

- checkstyle.xml
- pitest-ant/pom.xml
- pitest-groovy-verification/pom.xml
- pitest-java8-verification/pom.xml
- pitest-maven-verification/pom.xml
- pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java
- pitest-maven-verification/src/test/resources/pit-site-combined/pom.xml
- pitest-maven-verification/src/test/resources/pit-site-custom-config/pom.xml
- pitest-maven-verification/src/test/resources/pit-site-multiple-timestamped/pom.xml
- pitest-maven-verification/src/test/resources/pit-site-non-timestamped/pom.xml
- pitest-maven-verification/src/test/resources/pit-site-reportonly/pom.xml
- pitest-maven-verification/src/test/resources/pit-site-skip/pom.xml
- pitest-maven-verification/src/test/resources/pit-surefire-excludes/pom.xml
- pitest-maven-verification/src/test/resources/simplelogger.properties
- pitest-maven/pom.xml
- pitest/pom.xml
- pom.xml
> cleanup maven poms

- .travis.yml
- pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java
this results in #(jdk-versions) x #(maven-version) = 3 x 4 = 12 runs
> changed travis file to test against multiple versions of maven and jdk

- pitest-maven/src/main/java/org/pitest/maven/ScmMojo.java
- pitest-maven/src/test/java/org/pitest/maven/ScmMojoTest.java
- pom.xml
> Fixes for #132 (enhacement)

- pitest/src/main/java/org/pitest/mutationtest/report/xml/XMLReportListener.java
- pitest/src/test/java/org/pitest/mutationtest/report/xml/XMLReportListenerTest.java
First shot of an implementation.
> Implemented #248.

- pitest/src/main/java/org/pitest/help/Help.java
I saw some error messages that i found misleading so i changed them. 
see #260
> improve error messages

- pitest/src/main/java/org/pitest/util/Glob.java
- pitest/src/test/java/org/pitest/util/GlobTest.java
> Handle empty excludes

- pitest/src/main/java/org/pitest/junit/JUnitCompatibleConfiguration.java
- pitest/src/main/java/org/pitest/junit/JUnitTestClassIdentifier.java
- pitest/src/main/java/org/pitest/junit/JUnitVersion.java
- pitest/src/test/java/org/pitest/junit/JUnitTestClassIdentifierTest.java
It would be useful if @Category and @RunWith annotations placed on test superclasses could be considered too.
> Look for JUnit annotations up in class hierarchy too

- hackers_guide.txt
- pitest/src/main/java/org/pitest/classinfo/ClassInfoSource.java
- pitest/src/main/java/org/pitest/functional/F.java
- pitest/src/main/java/org/pitest/functional/F2.java
- pitest/src/main/java/org/pitest/functional/F3.java
- pitest/src/main/java/org/pitest/functional/F4.java
- pitest/src/main/java/org/pitest/functional/F5.java
- pitest/src/main/java/org/pitest/functional/F6.java
- pitest/src/main/java/org/pitest/functional/FunctionalIterable.java
- pitest/src/main/java/org/pitest/mutationtest/HistoryStore.java
- pitest/src/main/java/org/pitest/mutationtest/MutationEngineFactory.java
- pitest/src/main/java/org/pitest/mutationtest/build/MutationGrouper.java
- pitest/src/main/java/org/pitest/mutationtest/config/ReportDirCreationStrategy.java
- pitest/src/main/java/org/pitest/mutationtest/engine/gregor/MethodMutatorFactory.java
- pitest/src/main/java/org/pitest/mutationtest/engine/gregor/ZeroOperandMutation.java
- pitest/src/main/java/org/pitest/mutationtest/incremental/CodeHistory.java
- pitest/src/main/java/org/pitest/testapi/AbstractTestUnit.java
- pitest/src/main/java/org/pitest/testapi/ResultCollector.java
- pitest/src/main/java/org/pitest/testapi/TestPluginFactory.java
- pitest/src/main/java/org/pitest/testapi/TestUnitFinder.java
Tidies up some checkstyle warnings for a clean import into eclipse neon.
> Clean import

- pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java
https://logging.apache.org/log4j/2.x/log4j-api/apidocs/index.html
> Add Log4j 2.x API to default logging classes

- pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java
- pitest-maven/src/test/java/org/pitest/maven/RunDecisionTest.java
Today PIT told me that it will not run for a specific module of my project. I didn't unterstand why. I understood it only after looking the source of PIT.
The change in this PR should help users to understand easily why PIT will not run.
> Don't leave the user in the dark. Tell him and help him to understand why PIT skips its execution.

- pitest/pom.xml
Fixes https://github.com/hcoles/pitest/issues/422?
> Update Xstream to 1.4.10

- so_you_want_to_build_mutation_testing_system.md
This fix some typos I found while reading `so_you_want_to_build_mutation_testing_system.md`.
> Fix a few typos in so_you_want_to_build_mutation_testing_system.md

- pitest-entry/src/main/java/org/pitest/coverage/CoverageData.java
- pitest-entry/src/main/java/org/pitest/coverage/execute/DefaultCoverageGenerator.java
Report which tests are failing without a mutation at a glance.
> Report failing tests without mutation

- pitest-entry/src/main/java/org/pitest/coverage/execute/DefaultCoverageGenerator.java
- pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java
- pitest-entry/src/test/java/org/pitest/mutationtest/MutationCoverageReportSystemTest.java
- pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java
- pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java
- pitest-maven/src/main/java/org/pitest/maven/SurefireConfigConverter.java
- pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java
- pitest-maven/src/test/java/org/pitest/maven/SurefireConfigConverterTest.java
- pitest/src/main/java/org/pitest/mutationtest/config/TestPluginArguments.java
Added an option to ignore failing tests from coverage, activated from maven plugin
> Added skipFailingTests option from maven plugin

- pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/InlinedFinallyBlockFilter.java
- pitest/src/main/java/org/pitest/classinfo/ComputeClassWriter.java
- pitest/src/main/java/org/pitest/mutationtest/engine/gregor/config/Mutator.java
- pitest/src/test/java/org/pitest/functional/FArrayTest.java
- pitest/src/test/java/org/pitest/functional/FCollectionTest.java
- pitest/src/test/java/org/pitest/functional/predicate/NotTest.java
- pitest/src/test/java/org/pitest/testapi/execute/TestPitest.java
* Remove empty dangling JavaDoc comments
* Replace dangling JavaDoc comments by block comments
> Remove Dangling Javadoc Comments

- pitest-entry/src/main/resources/META-INF/services/org.pitest.mutationtest.build.MutationInterceptorFactory
> Filter try-with-resources before filtering inlined code

- pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/rv/UOI4Mutator.java
Fixes https://github.com/hcoles/pitest/issues/660
> UOI4 reports mutated field name

- pitest-maven-verification/src/test/resources/pit-263-yatspec/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- pitest-entry/src/main/java/org/pitest/bytecode/analysis/InstructionMatchers.java
- pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/InlinedFinallyBlockFilter.java
- pitest-entry/src/test/java/org/pitest/mutationtest/TestMutationTesting.java
- pitest-entry/src/test/java/org/pitest/mutationtest/config/PathNamePredicateTest.java
- pitest/src/main/java/org/pitest/functional/prelude/Prelude.java
- pitest/src/test/java/org/pitest/classpath/ClassPathTest.java
- pitest/src/test/java/org/pitest/functional/prelude/PreludeTest.java
Remove unused isNotNull and isNull from Prelude class
> replace Prelude.java.isEqualTo with java.util.function.Producer.isEqual.

- pitest-entry/src/main/java/org/pitest/mutationtest/config/SettingsFactory.java
- pitest/src/main/java/org/pitest/util/StringUtil.java
- pitest/src/test/java/org/pitest/util/StringUtilTest.java
replace StringUtil.join with java.lang.String.join
> replace StringUtil.join with java.lang.String.join

- pitest-entry/src/main/java/org/pitest/mutationtest/tooling/MutationCoverage.java
ie;
```
- Statistics
================================================================================
>> Line Coverage: 1041/1200 87%
>> Generated 600 mutations Killed 316 (53%)
>> Ran 1014 tests (1.69 tests per mutation)
```
> add Line Coverage on the console

- pitest/src/main/java/org/pitest/util/ManifestUtils.java
Building a String using concatenation (with '+') in a loop is considered a bad practice
Using a StringBuilder is more efficient:
https://stackoverflow.com/questions/18561424/using-for-strings-in-a-loop-is-it-bad-practice/18561542
> Remove String concatenation with '+' sign in loop

- .github/workflows/release.yml
- .gitignore
- perform_release.sh
- pitest-aggregator/pom.xml
- pitest-ant/pom.xml
- pitest-build-config/pom.xml
- pitest-command-line/pom.xml
- pitest-entry/pom.xml
- pitest-groovy-verification/pom.xml
- pitest-html-report/pom.xml
- pitest-java8-verification/pom.xml
- pitest-maven-verification/pom.xml
- pitest-maven/pom.xml
- pitest/pom.xml
- pom.xml
- prepare_release.sh
First release via automated flow.
> Release 1.6.1

- pitest-build-config/src/main/resources/pitest/checkstyle.xml
https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/naming/LambdaParameterNameCheck.html
> add LambdaParameterName module into checkstyle

- pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/EmptyObjectReturnValsMutator.java
> fix mutation message (emptyList -> emptySet)

- pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/experimental/BigDecimalMutator.java
- pitest/src/main/resources/META-INF/services/org.pitest.mutationtest.engine.gregor.MethodMutatorFactory
- pitest/src/test/java/org/pitest/mutationtest/engine/gregor/config/MutatorTest.java
- pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/BigDecimalMutatorTest.java
Hi @hcoles,
Thanks for outstanding project Pitest. I’m using it for years. Pitest let think outside the box about problem I'm workin on. 
I'm often doing calculation based on BigDecimal. My implementation is similar to BigIntegerMutator. I read conversation in https://github.com/hcoles/pitest/pull/518#issue-361311895, but I couldn't find reason to not implement BigDecimal mutator.
Could you review? Suggestions are always welcome.
Kindly regards,
> BigDecimal mutator

- README.md
- pitest-entry/src/main/java/org/pitest/process/WrappingProcess.java
- pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java
- pitest-maven-verification/src/test/resources/pit-jacoco/pom.xml
- pitest-maven-verification/src/test/resources/pit-jacoco/src/main/java/sources/DiscoveredClass.java
- pitest-maven-verification/src/test/resources/pit-jacoco/src/main/java/sources/MessageBuilder.java
- pitest-maven-verification/src/test/resources/pit-jacoco/src/test/java/tests/DiscoveredTest.java
- pitest-maven-verification/src/test/resources/pit-jacoco/src/test/java/tests/TestMessageBuilder.java
> remove jacoco agent from classpath if present

- pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java
- pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java
> avoid jboss logging by default

- pom.xml
detected at:
https://github.com/checkstyle/checkstyle/actions/runs/4396049302/jobs/7698238711#step:4:2371
```
$ cd target/site/
✔ ~/java/github/romani/checkstyle/target/site [master|✔] 
$ ag --hidden "pitest.org"
plugin-management.html
196:<td><a class="externalLink" href="http://pitest.org">pitest-maven</a></td>
```
> minor: update link to web site to avoid redirection

- pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/RegionIndex.java
- pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/RegionInterceptor.java
- pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/AssertFilter.java
- pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/ImplicitNullCheckFilter.java
- pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/MethodReferenceNullCheckFilter.java
- pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/StringSwitchFilter.java
- pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/TryWithResourcesFilter.java
- pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/javafeatures/ImplicitNullCheckFilterTest.java
Older filters not using the region system perform horifically when they encounter large methods.
> Improve performance of filters

- pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java
- pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java
> Fix the commandline options parsing

- pitest/src/main/java/sun/pitest/CodeCoverageStore.java
There is no way to lock a `ConcurrentHashMap` completely for calculations like it was done.
For that for example a `Collections.synchronizedMap(...)` is needed.
Using `compute(...)` the necessary logic can be done in an atomic way properly.
> Make the access to CLASS_HITS atomic

- pitest-maven/src/main/java/org/pitest/maven/SurefireConfigConverter.java
- pitest-maven/src/test/java/org/pitest/maven/SurefireConfigConverterTest.java
Fix for https://github.com/hcoles/pitest/issues/1238
> Handle comma separated excludedGroups

- pitest-entry/src/main/java/org/pitest/coverage/BasicStatListener.java
- pitest-entry/src/main/java/org/pitest/coverage/BasicTestStatListenerFactory.java
- pitest-entry/src/main/java/org/pitest/coverage/CompoundTestStatListener.java
- pitest-entry/src/main/java/org/pitest/coverage/NoTestStats.java
- pitest-entry/src/main/java/org/pitest/coverage/TestStatListener.java
- pitest-entry/src/main/java/org/pitest/coverage/TestStatListenerFactory.java
- pitest-entry/src/main/java/org/pitest/coverage/execute/DefaultCoverageGenerator.java
- pitest-entry/src/main/java/org/pitest/mutationtest/config/PluginServices.java
- pitest-entry/src/main/java/org/pitest/mutationtest/config/SettingsFactory.java
- pitest-entry/src/main/java/org/pitest/mutationtest/tooling/EntryPoint.java
- pitest-entry/src/main/java/org/pitest/util/Timings.java
- pitest-entry/src/main/resources/META-INF/services/org.pitest.coverage.TestStatListenerFactory
- pitest-entry/src/test/java/org/pitest/coverage/BasicStatListenerTest.java
- pitest-entry/src/test/java/org/pitest/coverage/CompoundTestStatListenerTest.java
- pitest-entry/src/test/java/org/pitest/mutationtest/ReportTestBase.java
- pitest-entry/src/test/java/org/pitest/mutationtest/TestMutationTesting.java
- pitest-entry/src/test/java/org/pitest/mutationtest/config/PluginServicesTest.java
- pitest-entry/src/test/java/org/pitest/mutationtest/config/SettingsFactoryTest.java
- pitest-entry/src/test/java/org/pitest/mutationtest/tooling/MutationCoverageReportTest.java
Report some basic test stats to the console to aid with debugging slow test suites.
> basic test stats
