pitest-maven/src/main/java/org/pitest/maven/PathToJavaClassConverter.java, pitest-maven/src/test/java/org/pitest/maven/PathToJavaClassConverterTest.java
In my environment my working directory is something like `/home/ankon/project-4.4/...`, and the pitest PathToJavaClassConverterTest failed because it treated the dot in the path as an indication for an extension.
Fix this by looking only at the file name itself.
I think there might be another issue here though: the translation from the file name to the regular expression should use `java.util.regex.Pattern#quote()` on each of the segments of the path, otherwise in my case both `project-4.4` and `project-4x4` etc would match.
=> Properly filter out files without extensions in paths containing a '.'

pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/main/java/org/pitest/maven/PitMojo.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java
Added a configuration element to allow classpath elements to be excluded from mutation testing, for the case when those elements might be troublesome. This mirrors the similar options in Surefire and Failsafe. Added a corresponding unit test to exercise the new config option.
I will be honest, I have not developed a Maven plugin before, so there may be a more efficient/idiomatic way to remove artifacts from the classpath being built up in the MojoToReportOptionsConverter -- so any suggestions or corrections there are welcome. :)
=> Added a configuration element to allow classpath elements to be excluded

pitest-maven/pom.xml, pitest-maven/src/main/java/org/pitest/maven/PitMojo.java
Hi,
Since maven 3.1.0, all logs are handled by slf4j.
http://maven.apache.org/maven-logging.html
But, pitest use both java.util.logging and System.out.
I just placed all logs under slf4j.
=> Got logs under slf4j

.travis.yml, pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java, pitest-maven-verification/src/test/resources/pit-site-reportonly/pom.xml, pitest-maven-verification/src/test/resources/pit-site-reportonly/src/main/java/com/example/Covered.java, pitest-maven-verification/src/test/resources/pit-site-reportonly/src/test/java/com/example/AnotherTest.java, pitest-maven/src/main/java/org/pitest/maven/report/PitReportMojo.java
While writing updates to the pit documentation, I noticed one of the user properties was wrong.  I updated the ``sourceDataFormats`` user property from ``${sourceDataFormats}`` to ``${pit.report.sourceDataFormats}``.  The original value was left over from before I settled on a naming strategy for the user properties.  The new value matches the convention for the reporting mojo's user properties to all start with "pit.report."
I added an integration test that verifies the build fails if the reporting mojo is executed without also executing the ``mutationCoverage`` goal.
I also noticed a build had failed because the integration tests ran too long without writing any output.  I added the travis_wait function to the .travis.yml file.  This addition causes a line to be outputted every  minute …
=> Minor Fixes for PIT Report Mojo

pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java
#194 Fix for test failing on Windows due to path separator being different.
Java always returns url paths as using '/' as separator, so using platform specific path separator was wrong at this point.
=> #194 Fix for test failing on Windows due to path separator being different

pom.xml
because the build does not run with maven 2.2.1 (see #198)
> [WARNING] Removing: jar from forked lifecycle, to prevent recursive invocation.
> [INFO] [checkstyle:check {execution: checkstyle}]
> [INFO] ------------------------------------------------------------------------
> [ERROR] BUILD ERROR
> [INFO] ------------------------------------------------------------------------
> [INFO] Failed during checkstyle execution
>
> Embedded error: Unable to find configuration file at location checkstyle.xml
> Could not find resource 'checkstyle.xml'.
> [INFO] ------------------------------------------------------------------------
> [INFO] For more information, run Maven with the -e switch
> [INFO] ------------------------------------------------------------------------
nobody fixed this for a …
=> set minimum version of maven to 3

pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationHtmlReportListener.java, pitest/src/main/resources/templates/mutation/style.css
- set monospaced font-family for sources' listings
- cache CSS when writing html report
@hcoles, do mind reviewing it? I believe monospaced text is better for displaying sources.
(the previous PR was send from my old account, I've deleted the account and closed the PR)
=> Small changes for HTML report generator

pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/ArgumentPropagationMutatorTest.java
Because the mutation engine is created with a filter for only mutating
methods with name "call" the old version of the test could never fail.
Changing the setup to mutate all methods, e.g.
```java
@Before
public void setupEngineToUseReplaceMethodWithArgumentOfSameTypeAsReturnValueMutator() {
createTesteeWith(True. <MethodInfo> all(), ARGUMENT_PROPAGATION_MUTATOR);
}
```
might also solve the issue but I don't know whether this has other unwanted side effects.
=> Argument propagation mutator: fix test setup for test case where no mutation is expected

pitest/src/main/java/org/pitest/coverage/CoverageData.java, pitest/src/main/java/org/pitest/util/Glob.java
I encountered a performance issue when testing PIT at our projects, which did not occur on some small sample projects I tested. After mutation testing was finished, PIT/PITclipse still needed hours to present the results. With profiling, I could trace it back to methods called during the creation of annotated source files (MutationHtmlReportListener.createAnnotatedSourceCodeLines()). Determining the classes contained in a file was very inefficient for large classpaths because some lists were iterated repeatedly. I therefore replaced this structure with a map for the lookups (and made regex matching a little more efficient). This brought runtime down to seconds on my machine.
I would have preferred filling the map in the constructor of CoverageData, but I had to make it lazy because …
=> performance improvements when annotating coverage

pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest/src/main/java/org/pitest/util/Glob.java
Hey,
We have some patterns that don't work well with the current implementation of globs. For example, we have Spock specs in packages like a.b.c.*Spec, a.b.c.integration.*Spec, a.b.c.integration.ui.*Spec, etc...  now the issue is that we want to run specs from the first 2 packages , but not from the last one and using a pattern like 'a.b.c.*Spec' or a.b.c.integration.*Spec (this is a subset of the first one with the current implementation) includes also the a.b.c.integration.ui.*Spec. 
In this PR we added a simple convention that if the glob starts with ~ (this is the regex operator in Groovy) we handle it as a Pattern regex. 
Let me know what you think
=> using regex in globs

pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java, pitest-maven-verification/src/test/resources/pit-263-yatspec/pom.xml, pitest-maven-verification/src/test/resources/pit-263-yatspec/src/main/java/sample/SomeClass.java, pitest-maven-verification/src/test/resources/pit-263-yatspec/src/test/java/sample/SomeClassTest.java, pitest/src/main/java/org/pitest/junit/JUnitCustomRunnerTestUnitFinder.java
This is a quick fix for #263 
As a long term solution, I think the list of runners in runnerCannotBeSplit should be part of the configuration
=> Quick fix for compatibility with yatspec runners

pitest/src/main/java/org/pitest/coverage/export/DefaultCoverageExporter.java, pitest/src/test/java/org/pitest/coverage/export/DefaultCoverageExporterTest.java
Currently, when reporting line coverage in XML format, methods are identified by name only. There will then be duplicate blocks in the report when there are overloaded methods. This pull request simply adds the method description along with the method name in the report so overloaded methods can be distinguished from one another in the report.
=> Modifying linecoverage reporter to include method desc

pitest/src/main/java/org/pitest/coverage/CoverageData.java
It's an error, after all. The build halts and `exit 1`. I think this log should be `severe` instead of `warn`.
=> When a test doesn't pass, the log should be severe

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-command-line/src/test/resources/testClassPathFile.txt, pitest/src/main/java/org/pitest/mutationtest/config/ConfigOption.java
- This option accepts the classpath in a file.(one element per line)
- This mitigates the issue where you are unable to run pitest on the
windows command line if the classpath is too big - issue #276
=> Add an option to supply the classpath in a file

README.md, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/test/java/org/pitest/maven/BasePitMojoTest.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java
Fix for issue 219 - packages filters will now be selected based on the compiled classes in the output dir.
This should simplify configuring pitest for use in multi module projects - in some cases the packages used vary by module.
As the maven plugin always sets the mutable path to match the output dir the primary purpose of this filter is to limit the instrumentation of classes during coverage.
It is still possible to explicitly set the target classes via the mojo to limit the analysis.
=> #90 auto selects classes instead of using group id

pitest-maven/src/main/java/org/pitest/maven/DependencyFilter.java, pitest/src/main/java/org/pitest/util/StringUtil.java
Changed the code of DependencyFilter so plugins are matched against Implementation-Vendor-Id instead of Implementation-Vendor. This way the plugin discovering is compliant with the default behavior in maven that sets groupId to Implementation-Vendor-Id in the META-INF/MANIFEST.MF
=> Use Implementation-Vendor-Id instead of Implementation-Vendor

pitest/src/main/java/org/pitest/mutationtest/engine/gregor/config/Mutator.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/NakedReceiverMutator.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/NakedReceiverMutatorTest.java
Mutator that replaces a method call with the object on which the method
is called in case the return type of the method matches the type of the
object.
It is named after @mbj mutation operator in [mutant](https://github.com/mbj/mutant) performing the same mutation.
=> Naked receiver mutator

pitest-java8-verification/src/test/java/com/example/java7/HasIfOnAStringEqualityInsideSwitchTestee.java, pitest-java8-verification/src/test/java/com/example/java7/HasIfOnAStringEqualityInsideSwitchTesteeTest.java, pitest-java8-verification/src/test/java/com/example/java7/HasIfOnAStringEqualityTestee.java, pitest-java8-verification/src/test/java/com/example/java7/HasIfOnAStringEqualityTesteeTest.java, pitest-java8-verification/src/test/java/com/example/java7/HasSwitchOnStringTestee.java, pitest-java8-verification/src/test/java/com/example/java7/HasSwitchOnStringTesteeTest.java, pitest-java8-verification/src/test/java/org/pitest/java7/verification/VerifyJava7IT.java, pitest/src/main/java/org/pitest/coverage/analysis/Block.java, pitest/src/main/java/org/pitest/mutationtest/filter/RemoveConditionalMutationForSwitchOnStringFilter.java, pitest/src/main/java/org/pitest/mutationtest/filter/RemoveConditionalMutationForSwitchOnStringFilterFactory.java, pitest/src/main/java/org/pitest/mutationtest/filter/support/ControlFlowAnalyserWrapper.java, pitest/src/main/java/org/pitest/mutationtest/filter/support/ControlFlowAnalyserWrapperImpl.java, pitest/src/main/java/org/pitest/mutationtest/filter/support/MutationOnSwitchInstructionLookup.java, pitest/src/main/java/org/pitest/mutationtest/filter/support/MutationOnSwitchInstructionLookupImpl.java, pitest/src/main/java/org/pitest/mutationtest/filter/support/Supplier.java, pitest/src/main/resources/META-INF/services/org.pitest.mutationtest.filter.MutationFilterFactory, pitest/src/test/java/org/pitest/mutationtest/filter/RemoveConditionalMutationForSwitchOnStringFilterTest.java, pitest/src/test/java/org/pitest/mutationtest/filter/support/MutationOnSwitchInstructionLookupImplTest.java
RemoveConditionalMutator_EQUAL_IF creates mutations for switch on string value and this mutations cannot be killed. This is fixed by implementing filter that removes this particular mutation in case when
it was done on switch instruction.
=> Implements #285

pitest/src/main/java/org/pitest/coverage/execute/ErrorListener.java
This will help to figure out why tests are failing without mutation
=> Make the stack trace visible in the logs when a test fails without mutation

.travis.yml, pitest-maven-verification/pom.xml, pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java, pitest-maven-verification/src/test/resources/pit-158-coverage/pom.xml, pitest-maven-verification/src/test/resources/pit-183-gwtmockito/pom.xml, pitest-maven-verification/src/test/resources/pit-263-yatspec/pom.xml, pitest-maven-verification/src/test/resources/pit-33-setUserDir/pom.xml, pitest-maven-verification/src/test/resources/pit-deterministic-coverage/pom.xml, pitest-maven-verification/src/test/resources/pit-process-hang/pom.xml, pitest-maven-verification/src/test/resources/pit-testng-jmockit/pom.xml, pitest/src/main/java/org/pitest/coverage/CoverageTransformer.java, pom.xml
test results can be seen here - https://travis-ci.org/kiftio/pitest/
- update maven-compiler, maven-source, maven-javadoc plugins
- update travis.yml to add oraclejdk9
- use system classloader if null passed to transformer in CoverageTransformer
Also a few tweaks in pitest-maven-verification to ensure projects are compiled with >= 1.6, and skipping a couple of tests (under java 9) that use powermock 1.x
=> build on java 9 with travis

pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationHtmlReportListener.java, pitest-html-report/src/test/java/org/pitest/mutationtest/report/html/MutationHtmlReportListenerTest.java, pitest/src/main/resources/templates/mutation/mutation_package_index.st, pitest/src/main/resources/templates/mutation/mutation_report.st, pitest/src/main/resources/templates/mutation/package_index.st, pitest/src/main/resources/templates/mutation/style.css
to fix issues 403 & 256
- Remove styles from html template and append to style.css
- Reference external stylesheet from html template
- Write out style.css when writing index page
The trickier/uglier part... Setting coverage complete width (green bar) without javascript or inline-styles.  I've added a class for each percentage in style.css and then setting the classname in the template.
=> load css from separate file to allow styles to be displayed in jenkins

pitest-maven/src/main/java/org/pitest/maven/ScmMojo.java
with the param originBranch and destinationBranch, you can run only the mutation test in the modified code. 
By example, It will allow to run the mutation test only on the impacted code of a PR. Moderne build factory can publish this report as comment of the PR ( or at least a link to the repport)
I test-it in my  project,(it work !) but I don't have any idea how create a IT test for this .
=> run only the mutation on the src who are in the origin branch but not in the destination branch

pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java
Prevent possible NPE and fix debug output if no tests exist.
=> Minor updates in MOJO base class

pitest-ant/src/main/java/org/pitest/ant/PitestTask.java, pitest-ant/src/test/java/org/pitest/ant/PitestTaskTest.java, pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigOption.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-groovy-verification/src/test/java/org/pitest/groovy/verification/TestJUnitConfigurationForSpock.java, pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java, pitest/src/main/java/org/pitest/junit/JUnitCompatibleConfiguration.java, pitest/src/main/java/org/pitest/junit/JUnitCustomRunnerTestUnitFinder.java, pitest/src/main/java/org/pitest/junit/JUnitTestPlugin.java, pitest/src/main/java/org/pitest/mutationtest/config/MinionSettings.java, pitest/src/main/java/org/pitest/mutationtest/config/TestPluginArguments.java, pitest/src/main/java/org/pitest/testapi/TestPluginFactory.java, pitest/src/main/java/org/pitest/testng/TestNGConfiguration.java, pitest/src/main/java/org/pitest/testng/TestNGPlugin.java, pitest/src/main/java/org/pitest/testng/TestNGTestUnit.java, pitest/src/main/java/org/pitest/testng/TestNGTestUnitFinder.java, pitest/src/test/java/org/pitest/TestJUnitConfiguration.java, pitest/src/test/java/org/pitest/junit/JUnitCompatibleConfigurationTest.java, pitest/src/test/java/org/pitest/junit/JUnitCustomRunnerTestUnitFinderTest.java, pitest/src/test/java/org/pitest/simpletest/SimpleTestPlugin.java, pitest/src/test/java/org/pitest/testng/TestNGConfigurationTest.java, pitest/src/test/java/org/pitest/testng/TestNGTestUnitFinderTest.java, pitest/src/test/java/org/pitest/testng/TestNGTestUnitTest.java
This is a pull request for issue #437 
I tried to be as close as possible to the naming convention and coding style of the project. I also made sure that the tests are running and I created a few new tests for the change.
The goal of this change is to filter the executed tests of a test class.  Hence, I added a new configuration parameter (includedTestMethods) for pitest in which you can put in a name (or names) of a test method and pitest only executes these methods for the targeted tests. The idea is to change the  *TestUnitFinder classes. There, I implemented something similar to the Category-based filtering mechanism.
=> Added configuration parameter to filter executed methods of target tests 

pitest-entry/pom.xml, pitest-entry/src/main/java/org/pitest/mutationtest/ClassHistory.java, pitest-entry/src/main/java/org/pitest/mutationtest/incremental/ObjectOutputStreamHistoryStore.java, pitest-entry/src/test/java/org/pitest/mutationtest/incremental/ObjectOutputStreamHistoryStoreTest.java, pitest/src/main/java/org/pitest/classinfo/ClassIdentifier.java, pitest/src/main/java/org/pitest/classinfo/ClassName.java, pitest/src/main/java/org/pitest/classinfo/HierarchicalClassId.java, pitest/src/main/java/org/pitest/functional/Option.java, pitest/src/main/java/org/pitest/mutationtest/MutationStatusTestPair.java, pitest/src/main/java/org/pitest/mutationtest/engine/Location.java, pitest/src/main/java/org/pitest/mutationtest/engine/MethodName.java, pitest/src/main/java/org/pitest/mutationtest/engine/MutationIdentifier.java
Unfortunately adds commons-codec as a dependency for base 64 encoding
(I experimented with DatatypeConverter, but needing to do --add-modules java.xml.bind when running java/javac in java 9 was proving problematic)
N.B. I've left the XStreamHistoryStore there and that is still the implementation used in EntryPoint.java
=> Object output stream history store

pitest-entry/src/main/java/org/pitest/coverage/export/DefaultCoverageExporter.java, pitest-entry/src/test/java/org/pitest/coverage/export/DefaultCoverageExporterTest.java
Test names are usually just method names which can be written in xml without escaping. However, when using Junit's parameterized tests, the test name can be any string the developer of the test choose to use.
Before this commit, if the test name include a quote, the generated xml is not valid.
By using `StringUtil.escapeBasicHtmlChars` on the test name, this commit ensures that any test name can be represented as a valid xml value.
For instance, before this commit, a test named `let's test this!` would have appeared in coverage xml file as `<test name='let's go test this!'/>` which is not valid xml. With this commit it will appear as `<test name='let&#39;s go test this!'/>`.
=> Escape test names when generating coverage xml file

pitest-aggregator/src/main/java/org/pitest/aggregate/ReportAggregator.java, pitest-aggregator/src/test/java/org/pitest/aggregate/ReportAggregatorBuilderTest.java
Currently, the ReportAggregator builder requires all code directories it works with to be non null, to exist, and to actually be directories. This is standard argument checking and it works just fine for most cases.
However, this behavior is problematic with some maven project structures.
In a maven project using submodules, one may choose to add a non standard source directory. This may be configured in the root pom and applied to all submodules. If this directory has a special purpose, for instance code generated by a given tool, it may not be used by all submodules.
In such a project, when listing source directories, plugins will see the additional source folder everytime, even for submodules where it is not used.
Because of the checks done in ReportAggregator, pitest report …
=> Ignore absent code directories when aggregating report

pitest-entry/src/test/java/org/pitest/coverage/export/DefaultCoverageExporterTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/report/xml/XMLReportListenerTest.java, pitest/src/main/java/org/pitest/util/StringUtil.java
This solve #468.
A parameterized test name can be anything, and it can even include the null-byte.
It seems that the null-byte is not part of the valid character range for xml (see [Character Range in xml](https://www.w3.org/TR/2006/REC-xml11-20060816/#NT-Char)), so we can not _encode_ it. But nothing prevents us from _representing_ it somehow, and this is what is proposed here.
With this PR, when we need to represent a null-byte in xml, we output `\0` instead. This is not perfect, reversible, a parser would not return a null-byte when reading `\0`, but I believe it to be good enough for reports generation.
=> produce valid xml for null-byte in test name

pitest-maven/src/main/java/org/pitest/maven/report/AbstractPitAggregationReportMojo.java, pitest-maven/src/main/java/org/pitest/maven/report/PitAggregationMojo.java, pitest-maven/src/main/java/org/pitest/maven/report/PitReportAggregationModuleMojo.java
There is two mojos for aggregated reports production :
- `PitAggregationMojo` that select modules to aggregate based on the dependencies of the module it runs in
- `PitReportAggregationModuleMojo` that is meant to run with command line and select modules to aggregate based on the submodules of the root project
Both mojos share a lot of behavior, some of it by calling the same objects (`ReportAggregator` for instance), some of it by code duplication. This make it complicated to make some changes that should apply to both mojos. (For instance, both mojos can only work if timestamped reports are disabled. Make them accept timestamped reports would require to make changes on both sides)
This pull request introduce an abstract class inherited by both mojo classes.
- `findDependencies` is made …
=> Refactor aggregation mojos

pitest-maven/src/main/java/org/pitest/maven/report/AbstractPitAggregationReportMojo.java
Aggregation mojos can't aggregate reports if they are timestamped. Since using timestamped reports is the default behavior, this make using aggregation more complicated for no good reason.
The logic for locating the latest report is already implemented in `ReportSourceLocator`. This pull request use a `ReportSourceLocator` in `AbstractPitAggregationReportMojo` to find the right report.
=> Allow aggregation of timestamped reports

pitest-entry/src/main/java/org/pitest/mutationtest/tooling/MutationCoverage.java
As discussed in #493, this makes easier to see the summary of the mutation testing by moving it to the bottom, together with the time stats, since both are small. Detailed info on each mutator appears first, requiring some scroll, since it probably (?) is not as useful in most cases as the remaining.
Let me know if you agree with this change @hcoles 
closes #493
=> Change report order to make stats summary appear last

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/MutationCoverage.java, pitest-entry/src/main/java/org/pitest/process/WrappingProcess.java, pitest/src/main/java/org/pitest/util/CommandLineUtils.java
This is a fix for this [issue](https://github.com/hcoles/pitest/issues/490)
> In case the test class path is very long, there is an option to supply the class path through a file classPathFile. However, we still run into problems starting the minions, because internally, Pitest doesn't seem to use a file to supply the class path to them
This solution will pack the class path into a jar file, that will be sent to the minions, whenever a class path **file** has been supplied to the MutationCoverage process. The class path jar file gets created in the same way as it does in Intellij. Here's some more background information about the problem: https://blog.jetbrains.com/idea/2017/10/intellij-idea-2017-3-eap-configurable-command-line-shortener-and-more/
=> Add support for passing long class paths to minions

pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationTestSummaryData.java, pitest-html-report/src/test/java/org/pitest/mutationtest/report/html/MutationTestSummaryDataTest.java
Hi!
This is a very minor enhancement of the HTML report.
When there are many mutators active, especially the experimental remove switch mutator than the active mutators list gets kind of messy.
So I changed the HashSet to a TreeSet to get a better overview of them.
Btw. if you agree I would also work on a little enhancement to aggregate mutators like the EXPERIMENTAL_REMOVE_SWITCH_MUTATOR_X to something like 
`EXPERIMENTAL_REMOVE_SWITCH_MUTATOR_[1-99]` in the active mutator list.
=> sorted mutators in html report

pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/experimental/RemoveSwitchMutator.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/experimental/RemoveSwitchMutatorTest.java
Hi, as I mentioned in my other PR here is also some minor enhancement to aggregate the EXPERIMENTAL_REMOVE_SWITCH_MUTATOR in the report.
Best regards,
ThLeu
=> provide aggregated name for mutator if generated as a collection

ISSUES.md, README.md
Hi @hcoles, as discussed together, this is first draft for a set of rules we could apply to be able to work more efficiently with pitest issues.
Anyone should feel free to comment, and propose changes. Once we agree, we can start applying those rules.
The main point of this PR is the `ISSUES.md` file. I also made some changes in `README.md` : in order to have a link to the issue policy that's visible enough I folded most of the versions list. This is easy to undo if needed.
=> Add some rules regarding issues management

hackers_guide.txt, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/MutationCoverage.java
Recently used pitest for the first time and noticed a typo in a log message.
Fixed that typo.
Fixed some additional typos in the `hackers_guide.txt` as I was reading it, as well as added a little information for IntelliJ. (Note: running `mvn clean install` in IntelliJ results in Build Success, so I guess the thing about the groovy plugin mentioned for Eclipse is not relevant to IntelliJ.)
Let me know if you want any changes. :)
=> Fix typos and add info for IntelliJ

pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/main/java/org/pitest/maven/ScmMojo.java, pitest-maven/src/test/java/org/pitest/maven/BasePitMojoTest.java, pitest-maven/src/test/java/org/pitest/maven/PitMojoTest.java
As highlighted by https://github.com/hcoles/pitest/issues/539, throwing a `NullPointerException` when the plugin configuration contains an empty element is not the most user friendly behavior.
This pull request change `AbstractPitMojo` getters to filter out nulls from lists. This way, empty elements in configuration will be ignored.
Before the actual bug fix, fields were made private and getters and setters were created as needed.
*PR history:*
A first version of this PR replaced `ArrayList` fields and return types by `List`. This was removed to keep compatible with maven 2.
=> Ignore empty element from plugin configuration

pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/rv/CRCR1Test.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/rv/CRCR2Test.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/rv/CRCR3Test.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/rv/CRCR4Test.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/rv/CRCR5Test.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/rv/CRCR6Test.java
This fixes the first compile issue I ran into when compiling the project on windows. ( See https://github.com/hcoles/pitest/issues/311#issuecomment-462561250 )
Inner classes are stored as separate class files under the target directory. In these tests, it has 2 inner classes named `HasIntegerLDC` and `HasIntegerLdc`. Unfortunately, windows doesn't allow the 2 files with the same name in different cases. The fix is to just rename the inner classes that conflict.
In checkstyle project, we ensure our project can compile on windows by using appveyor CI. Pitest could consider using it too.
=> fixed compile issues with CRCR tests on windows

pitest-ant/src/main/java/org/pitest/ant/PitestTask.java, pitest-ant/src/test/java/org/pitest/ant/PitestTaskTest.java
The ant documentation mentions test plugins should be placed with the ant plugin, but the ant plugin doesn't support the `--testPlugin` parameter to choose which one to use.  This adds support for it.
While I was at it, I noticed it also didn't support `--failWhenNoMutations` so I added that too.
=> Add support for testPlugin and failWhenNoMutations to ant plugin

README.md
Because of a comment on https://github.com/hcoles/pitest/pull/528, I noticed that this PR was not mentioned in the version content. This PR put it in the list.
The same change should be done on the github release.
=> Add missing PR from release 1.4.4 description

pitest/src/main/java/org/pitest/coverage/CoverageClassVisitor.java, pitest/src/main/java/org/pitest/coverage/analysis/ArrayProbeCoverageMethodVisitor.java, pitest/src/main/java/org/pitest/util/StreamUtil.java
The coverage changes I introduced in 1.4.7 will break if more that `Short.MAX_VALUE` classes are loaded - this patch resolves that limitation.
This patch also adds a defensive `Thread.interrupted()` check before copying class data in the `JavassistCoverageInterceptor`. The NIO utilities will throw a `ClosedByInterruptException` if the thread was interrupted (and didn't have its flag cleared) before these methods are called. Poorly-behaved tests might interrupt a thread, not clear the interrupt flag, then trigger class loading, which would then result in this exception.
=> Fixes for issue 597

pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java
This will avoid the constant keyboard focus loss on mac that is mentionned un #581.
=> Make child JVM headless by default

pitest-entry/src/main/java/org/pitest/coverage/execute/DefaultCoverageGenerator.java
I ran into that in https://github.com/szpak/gradle-pitest-plugin/issues/129 - when the testng plugin was not enabled.
If I understand correctly that error message means that no JUnit 4.6+ is on a classpath and no test plugin is enabled for other test tools (assuming they are on a classpath).
Feel free to adjust the message to your preferences.
=> Enhance error message on not enabled test plugin

.travis.yml
I initially wanted to just add OpenJ9 11 build on Travis, but along the way I also added builds for newer Java versions and simplified a build matrix (newer Java versions are available out-of-box).
The Java 12 build [fails](https://travis-ci.org/szpak/pitest/jobs/530166058) - among other as 1.6 as a class level is no longer supported. I left it as "allow_failures" to have it fixed by you on your own way (a basic smoke test in my Gradle plugin works [fine](https://travis-ci.org/szpak/gradle-pitest-plugin/jobs/530015469) with Java 12 in general)
In addition there is a [problem](https://travis-ci.org/szpak/pitest/jobs/530162313#L7842) with PowerMock and OpenJ9 8. It's a [known limitation](https://github.com/powermock/powermock/issues/970) and I don't know if you want to bother with that (so …
=> OpenJ9 11 Travis build + some other Travis changes

pitest/src/main/java/org/pitest/mutationtest/mocksupport/BendJavassistToMyWillTransformer.java
The BendJavassistToMyWillTransformer must use the ComputeClassWriter instead of ASM's default ClassWriter, since it will inevitably try to compute frames for javassist classes. If an application has already loaded a javassist class in a lower level class loader (e.g. not in the system boot classloader, where pit is), then this will cause a LinkageError for duplicate class loading.
This should fix #613
=> Fix for #613: Avoid loading Javassist classes into the boot class loader

pitest/src/main/java/org/pitest/mutationtest/engine/gregor/config/Mutator.java
Without this change, you can only configure AOD2 (but called AOD1) manually,
and if you configure ALL, you get AOD2.
Only if add the complete AOD group, you get both.
=> Fix Mutator map key for AOD2

pitest/src/main/java/org/pitest/classpath/CompoundClassPathRoot.java
Without this change, the calculated class path starts with `;`, which causes the current working directory to be part of the classpath.
This can greatly falsify the results.
In my case I had a dumped classfile in the current working directory, and as the current working directory was in the start of the class path, it was taken instead of the real class.
This PR fixes that behavior.
=> Do not include the current directory to the minion class path

pitest/src/main/java/org/pitest/testapi/Description.java
=> Do not print the class name twice for unsplittable test units

pitest-maven-verification/src/test/resources/pit-testng-jmockit/pom.xml, pitest-maven-verification/src/test/resources/pit-testng/pom.xml, pitest/src/main/java/org/pitest/testng/TestNGTestUnit.java, pom.xml
Bump the TestNG version to 6.9.10 and force the use of TestNG.addListener(ITestNGListener).
TestNG 7.0.0 removed various deprecated specialized TestNG.addListener methods.
Using TestNG.addListener(ITestNGListener) explicitly keeps PITest binary-compatible with the new TestNG 7.x releases.
This fixes #634
=> TestNG 7.0.0 compatibility

pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/javafeatures/TryWithResourcesFilterTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/logging/LoggingCallsFilterTest.java, pitest-entry/src/test/java/org/pitest/plugin/export/MutantExportInterceptorTest.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/config/GregorEngineFactory.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/config/Mutator.java
The new mutators set provides more stable return type mutators with a more easily understood behaviour. There were concerns that it may result in increased numbers of equivalent mutators, but the filters for these seem to be working well.
This PR renames the NEW_DEFAULTS mutator set to DEFAULTS and create a group called OLD_DEFAULTS to allow access to the original set.
History files will be invalidated by this change and should be deleted when upgrading.
=> Turns on the new mutator set by default

pitest-build-config/src/main/resources/pitest/checkstyle.xml, pom.xml
old version of 2.15 was using checkstyle 6.1.1 by default.
new version of 3.1.0 is using checkstyle 8.19 by default.
This is still not the latest version of checkstyle.
=> bump maven-checkstyle-plugin to 3.1.0

pitest-maven/pom.xml, pom.xml
Upgraded versions of vulnerable transitive dependencies in pitest-maven and adding the OWASP Dependency Check plugin to the pitest-parent POM
Upgraded versions of vulnerable transitive dependencies, placing them immediately before the dependencies where they are used to ensure that Maven excludes the transitive dependencies:
- commons-collections, commons-beanutils, and plexus-utils are all used by maven-reporting-impl
- groovy-all is a transitive dependency of maven-scm-providers-standard.  It is used by maven-scm-provider-integrity
Added the OWASP Dependency Check plugin to the pitest-parent POM to allow it to be run in any module.
=> #723 Upgraded versions of vulnerable transitive dependencies in pitest-maven

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigOption.java
To make it possible to use from the Gradle plugin.
Fixes: https://github.com/szpak/gradle-pitest-plugin/issues/175.
=> Add skipFailingTests flag to command line PIT

pitest-entry/src/main/java/org/pitest/coverage/execute/DefaultCoverageGenerator.java
Someone from the mailing list [understood](https://groups.google.com/d/msg/pitusers/ZSjeBaEDh2s/PIgisRbtAgAJ) recently that JUnit 5.x satisfies the "JUnit 4.6+" requirement.
=> Improve error message on non-enabled JUnit 5 plugin

pitest-ant/src/main/java/org/pitest/ant/PitestTask.java, pitest-ant/src/test/java/org/pitest/ant/PitestTaskTest.java
There didn't seem to be ANT support for the `fullMutationMatrix` option described in #510 (issue) and #511 (pr), so I've added it.
I mimicked what [this PR](https://github.com/hcoles/pitest/pull/573) did to add ANT support for another feature. After doing this and producing a new set of jars, I was able to get a mutation matrix.
=> ANT support for the fullMutationMatrix option

README.md
Setting minimal version required for Java 14 testing in gradle-pitest-plugin I've founded that it isn't precised in README or release notes (which also could be updated).
=> Precise minimal version for Java 14 in README

pitest-entry/src/main/java/org/pitest/bytecode/analysis/MethodTree.java, pitest-entry/src/main/java/org/pitest/coverage/CoverageData.java, pitest-entry/src/main/java/org/pitest/mutationtest/MutationStatusMap.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/CompoundMutationInterceptor.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/DefaultTestPrioritiser.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/MutationTestBuilder.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/InlinedFinallyBlockFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/SettingsFactory.java, pitest-entry/src/main/java/org/pitest/mutationtest/execute/MutationAnalysisExecutor.java, pitest-entry/src/main/java/org/pitest/mutationtest/statistics/MutationStatisticsPrecursor.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/DirectorySourceLocator.java, pitest-entry/src/main/java/org/pitest/mutationtest/verify/DefaultBuildVerifier.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/AnalyisPriorityComparatorTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/TestInfoPriorisationComparatorTest.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/Line.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationResultList.java, pitest-html-report/src/test/java/org/pitest/mutationtest/report/html/MutationTestSummaryDataFileNameComparatorTest.java, pitest-html-report/src/test/java/org/pitest/mutationtest/report/html/ResultComparatorTest.java, pitest/src/main/java/org/pitest/coverage/analysis/ControlFlowAnalyser.java, pitest/src/main/java/org/pitest/coverage/execute/CoverageWorker.java, pitest/src/main/java/org/pitest/dependency/DependencyExtractor.java, pitest/src/main/java/org/pitest/functional/FCollection.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/config/Mutator.java, pitest/src/test/java/org/pitest/functional/FCollectionTest.java, pitest/src/test/java/org/pitest/functional/prelude/PreludeTest.java, pitest/src/test/java/org/pitest/util/StringUtilTest.java
use java 8 features: List.sort, Comparator.comparing and others
=> use java 8 features: List.sort, Comparator.comparing and others

pitest-entry/pom.xml, pitest-entry/src/main/java/org/pitest/coverage/CoverageData.java, pitest-entry/src/main/java/org/pitest/mutationtest/incremental/IncrementalAnalyser.java, pitest-entry/src/test/java/org/pitest/mutationtest/incremental/IncrementalAnalyserTest.java
fixes #763
Incremental analysis honors all killing tests now instead of limiting the scope of analysis to the first killing test.
This is often identical if there is no matrix mutation in place but TestNG plugin calculates test units in terms of test classes thus executes all test methods of a test class and records historic data
with method level granularity and class level granularity. We need to take all killing tests into account to match history data and executable test units in the analyzer. This will also help if different test classes cover a certain production class and one of those test classes is deleted or renamed.
Improved logging to help spotting analyzer misbehaviour. Although pitest is already verbose I added another info-level statement.
I've also refactored the test and …
=> Allowed more tests to be considered killing a mutant when using historic data (fixes #763)

pitest-ant/src/main/java/org/pitest/ant/PitestTask.java, pitest-ant/src/test/java/org/pitest/ant/PitestTaskTest.java, pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/MutationCoverageReport.java, pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigOption.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-entry/src/main/java/org/pitest/mutationtest/statistics/MutationStatistics.java, pitest-entry/src/main/java/org/pitest/mutationtest/statistics/MutationStatisticsPrecursor.java, pitest-entry/src/main/java/org/pitest/mutationtest/statistics/Score.java, pitest-entry/src/main/java/org/pitest/mutationtest/statistics/ScorePrecursor.java, pitest-entry/src/test/java/org/pitest/mutationtest/statistics/MutationStatisticsPrecursorTest.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationTestSummaryData.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationTotals.java, pitest-html-report/src/main/resources/templates/mutation/mutation_package_index.st, pitest-html-report/src/main/resources/templates/mutation/package_index.st, pitest-html-report/src/test/java/org/pitest/mutationtest/report/html/MutationTestSummaryDataTest.java, pitest-html-report/src/test/java/org/pitest/mutationtest/report/html/MutationTotalsTest.java, pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/test/java/org/pitest/maven/PitMojoTest.java, pitest/src/main/java/org/pitest/mutationtest/DetectionStatus.java
Hello @hcoles, first of all thanks a lot for this project!
This PR is to address enhancement #128 as I would find it useful as well.
=> Add test strength statistic

pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java
Hi,
I would like to suggest a fix for the issue #464 when `jvmArgs` property is not being picked up by `pitest-maven-plugin` if passed through the CLI.
For example, in the case when I can't make any changes in `pom.xml` I would like to be able to supply the argument (e.g. `-DjvmArgs=-ea`) through the CLI and expect it to be injected into the plugin. 
Thank you,
Yuriy
=> Add missing property for jvmArgs parameter #464

pitest-entry/src/main/java/org/pitest/mutationtest/incremental/ObjectOutputStreamHistoryStore.java, pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestMinion.java
We have 2 cases where a boxed primitive is created from a String, just to extract the unboxed primitive value 
It is more efficient to just call the static parseXXX method
Problem: 
The goal is to convert a String to an int and its currently being done like this:
String => **int => Integer** => int                
^ This is inside Integer.valueOf
Where a more efficient way of converting is by doing:
**String => int**
^ Integer.parseInt
=> Parse String directly to primitive type

pitest/src/main/java/org/pitest/classpath/ClassPath.java, pitest/src/main/java/org/pitest/util/ManifestUtils.java
With its name matching "classpath*.jar".
Fixes #822.
=> Mitigate chance to get NPE on accidental dependency

.github/workflows/release.yml, .gitignore, perform_release.sh, pitest-aggregator/pom.xml, pitest-ant/pom.xml, pitest-build-config/pom.xml, pitest-command-line/pom.xml, pitest-entry/pom.xml, pitest-groovy-verification/pom.xml, pitest-html-report/pom.xml, pitest-java8-verification/pom.xml, pitest-maven-verification/pom.xml, pitest-maven/pom.xml, pitest/pom.xml, pom.xml, prepare_release.sh
Release automatically when code is merged into the release branch.
The maven release plugin is no longer used, instead tracking of the
build number is moved into git, where the minor version is tracked as a tag.
Updating the major version requires manual changed to the poms, which
needs to be addressed in the future, but fortuantely major version
updates are rare.
If a major version is changed the minor version must be reset. This can be done with
```bash
git tag -d build-number-<x>
git push --delete origin build-number-<x>
```
Where `x` is the current build number.
The current development version is always x.x.0-SNAPSHOT.
=> Automatically release to maven central

.github/workflows/ci.yml, .gitignore, pitest-entry/src/test/java/com/example/coverage/execute/samples/simple/ParentChildInitializationTest.java, pitest-entry/src/test/java/org/pitest/coverage/execute/CoverageProcessSystemTest.java, pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java, pitest-maven-verification/src/test/resources/pit-enum-constructor-npe/pom.xml, pitest-maven-verification/src/test/resources/pit-enum-constructor-npe/src/main/java/com/example/Test.java, pitest-maven-verification/src/test/resources/pit-enum-constructor-npe/src/test/java/test/com/example/NestedClassTest.java, pitest/src/main/java/org/pitest/coverage/CoverageClassVisitor.java, pitest/src/main/java/org/pitest/coverage/analysis/ArrayProbeCoverageMethodVisitor.java, pitest/src/test/java/org/pitest/util/PitXmlDriver.java, pitest/src/test/java/org/pitest/util/XStreamCloning.java
Fixes #770 and #746 based on work by @LaurentTho3
=> Handle parent before child initialisation order

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/MutationCoverageReport.java
Currently when maxSurviving is set to 0, an error will still not be thrown due to this restriction `if ((threshold > 0)` in src/main/java/org/pitest/mutationtest/commandline/MutationCoverageReport.java in `throwErrorIfMoreThanMaxSuvivingMutants`.
We can safely set it to `if ((threshold >= 0)` as the default is -1.
This should finish the fixes that were started to address this issue: [https://github.com/hcoles/pitest/issues/269](https://github.com/hcoles/pitest/issues/269).
Also fixed a typo in that method's name changing `throwErrorIfMoreThanMaxSuvivingMutants` to `throwErrorIfMoreThanMaxSurvivingMutants`.
Let me know if any additional information/clarification from me would be helpful.
Thanks!
=> Fixed tests not failing when maxSurviving=0 and typo

pitest-html-report/src/main/resources/templates/mutation/style.css
Adds missing css styles for less common outcomes, lines were appearing unstyled at the end of the report as a result.
=> add missing upper case styles

pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java
Support for `mutateStaticInitializers` was removed some time ago, but the config value was accidentally left in place.
=> remove dead static initialiser option

pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/EntryPoint.java
At some point the performance of the history store has regressed substantially. This performance hit is being taken even when the history store is not in use. This change ensures a no-op history store is used unless history recording is requested.
Performance regression will be addressed seperately.
=> do not create history store when not required

pitest-aggregator/src/main/java/org/pitest/aggregate/ReportAggregator.java, pitest-entry/src/main/java/org/pitest/coverage/CoverageData.java, pitest-entry/src/main/java/org/pitest/coverage/CoverageDatabase.java, pitest-entry/src/main/java/org/pitest/coverage/LegacyClassCoverage.java, pitest-entry/src/main/java/org/pitest/coverage/ReportCoverage.java, pitest-entry/src/test/java/org/pitest/coverage/CoverageDataTest.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/AnnotatedLineFactory.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationHtmlReportListener.java, pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java, pitest/src/main/java/org/pitest/classinfo/ClassName.java
Writing history information is stupidly slow for larger codebases as it collates class level coverage data from instruction level data with OMG complexity.
This change drives the history off of the legacy line coverage information, which was previously lazily calculated. Since a recent change this information is also used by the report aggregation system. To prevent accidental breakage by using data not present at aggregate time, the line coverage data has been hived off into a seperate class.
This horrific mess and needs revisting.
=> History performance

pitest-entry/src/test/java/org/pitest/coverage/execute/CoverageProcessSystemTest.java, pitest/src/main/java/org/pitest/junit/JUnitCompatibleConfiguration.java, pitest/src/main/java/org/pitest/mutationtest/config/MinionSettings.java, pitest/src/main/java/org/pitest/mutationtest/config/PrioritisingTestConfiguration.java, pitest/src/main/java/org/pitest/mutationtest/config/PrioritisingTestSuiteFinder.java, pitest/src/main/java/org/pitest/mutationtest/config/PrioritisingTestUnitFinder.java, pitest/src/main/java/org/pitest/testapi/Configuration.java, pitest/src/main/java/org/pitest/testng/TestNGConfiguration.java, pitest/src/test/java/org/pitest/mutationtest/config/PrioritisingTestConfigurationTest.java
Adds support for multiple pitest test plugins. Pitest will attempt to use any testengine placed on its classpath, trying them in order of precedence. A test plugin must either completely handle a test class, or not handle it at all.
This enables support for legacy projects that mix Junit and TestNG.
As a result of this change the 'testPlugin' parameter is now redundant, but has been retained for this release.
=> allow multiple test engines

pitest/src/main/java/org/pitest/mutationtest/engine/gregor/config/Mutator.java
Fix for #916.
Would be extremely helpful for the PITclipse Plug-in. See [Issue 114 of PITclipse](https://github.com/pitest/pitclipse/issues/114)
=> Added the option to get all mutator IDs

pitest/src/main/java/org/pitest/mutationtest/engine/gregor/GregorMutater.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/MutatingClassVisitor.java
The order of iteration of a hashset is not guaranteed. It is unclear if
this has any observable consequences, but determinism is always
preferable, and aids debugging.
The order that operators applied is now explicitly based on the mutator
id. It is unclear if there is any benefit to the de-deplication
performed by the HashSet, but this has been retained.
=> Guarantee order of mutation operators

README.md, pitest-entry/src/main/java/org/pitest/bytecode/analysis/MethodTree.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/equivalent/NullFlatMapFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/equivalent/NullFlatMapFilterFactory.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/ImplicitNullCheckFilter.java, pitest-entry/src/main/resources/META-INF/services/org.pitest.mutationtest.build.MutationInterceptorFactory, pitest-entry/src/test/java/com/example/HasPrivateStreamMethodUsedOnlyInSingleFlatMap.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/MutationDiscoveryTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/equivalent/NullFlatmapTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/javafeatures/FilterTester.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/NullMutateEverything.java
Flat map treats null and Stream.empty() equivalently, so when return `Stream.empty()` is mutated to `return null` the mutant survives.
This change filters out mutants of this type if
* the mutant is in a private method
* the method is only called via flatMap
=> Null flatmap

pitest-aggregator/src/main/java/org/pitest/aggregate/BlockCoverageDataLoader.java, pitest-aggregator/src/main/java/org/pitest/aggregate/DataLoader.java, pitest-aggregator/src/main/java/org/pitest/aggregate/MutationResultDataLoader.java, pitest-aggregator/src/main/java/org/pitest/aggregate/ReportAggregator.java, pitest-aggregator/src/test/java/org/pitest/aggregate/DataLoaderTest.java, pitest-aggregator/src/test/resources/snippets/linecoverage.xml, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationTestSummaryData.java, pitest-maven/src/main/java/org/pitest/maven/report/AbstractPitAggregationReportMojo.java
- #621: do not use test dependencies as test source directories
- #622: use the name of the mutator (it is not a class name written in mutations.xml)
=> fix(report-aggregate) Fix report aggregation

pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/equivalent/EquivalentReturnMutationFilter.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/equivalent/EquivalentReturnMutationFilterTest.java
Ignore label nodes introduced by try catch block when filtering boxed
return true and return false mutants.
=> filter boxed return constant boolean mutant in try

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigOption.java
The gradle plugin seems to auto supply this parameter when not specified
by the user, resulting in an error.
Reintroducing for now, until gradle plugin is updated.
=> reintroduce testPlugin parameter on command line

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigOption.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java
Although the parameter is currently unused, it would be useful in the
future to be able to identify the base dir of a project. For gradle
project this only seems to be possible from within the build script
itself.
This parameter is therefore being added without functionality so the
gradle plugin can be updated in advance.
=> support passing project base

pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/ArgumentPropagationMutatorTest.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/experimental/NakedReceiverMutatorTest.java, pitest/src/test/java/org/pitest/verifier/mutants/IntMutantVerifier.java, pitest/src/test/java/org/pitest/verifier/mutants/LongMutantVerifier.java, pitest/src/test/java/org/pitest/verifier/mutants/MutantVerifier.java, pitest/src/test/java/org/pitest/verifier/mutants/MutatorVerifier.java, pitest/src/test/java/org/pitest/verifier/mutants/MutatorVerifierStart.java, pitest/src/test/java/org/pitest/verifier/mutants/NullMutator.java
Introduces new mutant verifier approach, allow mutators to be tested
without serialising with xstream.
=> fix tests to run on java 18

pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/timeout/AvoidForLoopCounterFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/timeout/InfiniteLoopFilter.java, pitest-entry/src/test/java/org/pitest/mutationtest/MutationCoverageReportSystemTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/timeout/AvoidForLoopCounterTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/timeout/InfiniteLoopBaseTest.java
Broadens analysis to avoid for loop counters. Previously loops comparing to small integers with specialised opcodes were not picked up.
=> filter loops with small integer comparison constant

README.md, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/EnumConstructorFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/staticinitializers/StaticInitializerInterceptor.java, pitest-entry/src/test/java/com/example/staticinitializers/SingletonWithWorkInInitializer.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/MutationDiscoveryTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/staticinitializers/StaticInitializerInterceptorTest.java
Filters mutations in constructor's called from the same class' static initializer.
A check is not made that the constructor is private. Some killable mutants may therefore be filtered, but this needs to be weighed against the confusion caused by mutants appearing/disappearing based on code visibility.
=> filter singleton constructors as per #903

pitest-aggregator/src/main/java/org/pitest/aggregate/ReportAggregator.java, pitest-ant/src/main/java/org/pitest/ant/PitestTask.java, pitest-ant/src/test/java/org/pitest/ant/PitestTaskTest.java, pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigOption.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/DirectorySourceLocator.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/MutationCoverage.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/SmartSourceLocator.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/HtmlReportFactory.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationHtmlReportListener.java, pitest-html-report/src/main/resources/templates/mutation/mutation_package_index.st, pitest-html-report/src/main/resources/templates/mutation/mutation_report.st, pitest-html-report/src/main/resources/templates/mutation/package_index.st, pitest-html-report/src/test/java/org/pitest/mutationtest/report/html/MutationHtmlReportListenerTest.java, pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/main/java/org/pitest/maven/report/AbstractPitAggregationReportMojo.java, pitest-maven/src/main/java/org/pitest/maven/report/PitReportMojo.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java
Based on work by @qxo in #799
Finally fixes #637
=> Support different input and output encodings

README.md, pitest/src/main/java/org/pitest/util/Glob.java, pitest/src/test/java/org/pitest/util/GlobTest.java
Fix by @ali-ghanbari with added test case. Allows file paths with +
symbols. There is still a larger issue here with the globs being
converted to regexs that needs to be resolved.
=> Allow plus in file paths

pitest-maven-verification/pom.xml, pitest-maven-verification/src/test/resources/pit-site-combined/pom.xml, pitest-maven-verification/src/test/resources/pit-site-custom-config/pom.xml, pitest-maven-verification/src/test/resources/pit-site-multiple-timestamped/pom.xml, pitest-maven-verification/src/test/resources/pit-site-non-timestamped/pom.xml, pitest-maven-verification/src/test/resources/pit-site-reportonly/pom.xml, pitest-maven-verification/src/test/resources/pit-site-skip/pom.xml, pitest-maven-verification/src/test/resources/pit-site-timestamped/pom.xml, pitest-maven/pom.xml, pitest-maven/src/main/java/org/pitest/maven/report/AbstractPitAggregationReportMojo.java, pitest-maven/src/main/java/org/pitest/maven/report/PitReportMojo.java, pitest-maven/src/test/java/org/pitest/maven/report/PitReportMojoTest.java, pom.xml
This **breaks backward compatibility** with `maven-site-plugin:3.4.x` and possibly other old versions as well. A revision bump is recommended.
This commit updates the Maven plugin-related dependencies and modifies any code affected by breaking changes. Note, some artifact versions were specified using a common property. However, it appears those artifacts no longer follow the same versioning scheme.
Closes #1037
=> Support Maven Site Plugin 3.12.0+

pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestMinion.java, pitest/src/test/java/org/pitest/mutationtest/execute/MutationTestMinionTest.java
=> mitigation for process hangs

pitest-entry/src/main/java/org/pitest/coverage/execute/CoverageProcess.java, pitest-entry/src/main/java/org/pitest/coverage/execute/DefaultCoverageGenerator.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/MutationTestUnit.java, pitest-entry/src/main/java/org/pitest/mutationtest/execute/MutationTestProcess.java, pitest-entry/src/main/java/org/pitest/process/WrappingProcess.java, pitest-entry/src/main/java/org/pitest/util/CommunicationThread.java, pitest-entry/src/test/java/org/pitest/mutationtest/MutationCoverageReportSystemTest.java, pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestMinion.java, pitest/src/main/java/org/pitest/util/ExitCode.java
Root cause of #1047 seems to be processes that are unable to start due
to insufficient memory. This results in the main process hanging,
waiting for their signal.
At some point the checks that the minion processes are alive look to
have been removed. This change reintroduces them with a simple poll.
=> poll minion processes to check they are alive

README.md, pitest-ant/src/main/java/org/pitest/ant/PitestTask.java, pitest-ant/src/test/java/org/pitest/ant/PitestTaskTest.java, pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigOption.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/EntryPoint.java, pitest-entry/src/main/java/org/pitest/process/ArgLineParser.java, pitest-entry/src/main/java/org/pitest/process/LaunchOptions.java, pitest-entry/src/main/java/org/pitest/process/WrappingProcess.java, pitest-entry/src/test/java/org/pitest/mutationtest/ReportTestBase.java, pitest-entry/src/test/java/org/pitest/mutationtest/TestMutationTesting.java, pitest-entry/src/test/java/org/pitest/process/ArgLineParserTest.java, pitest-entry/src/test/java/org/pitest/process/WrappingProcessTest.java, pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java
Surefire and other plugins support the `argLine` property for passing
parameters to child jvms in the form of a single string.
Pitest currently supports passing a list of properties using the jvmArgs
param. This requires duplicating values already specified in the
argLine.
The list format also causes problems when the arguments contain
delimiters, for which some unsatisfactory workarounds have been applied.
This change adds a new argLine property to pitest, which is read from
the standard maven property by default. It can be set explicitly for Ant
and the command line.
The existing jvmArgs parameter is retained, and can be used to set
additional arguments for pitest.
fixes #1052
=> Support for standard argLine

README.md, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/autoconfig/KeepMacOsFocus.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/CompoundConfigurationUpdater.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigurationUpdater.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/PluginServices.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/SettingsFactory.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/EntryPoint.java, pitest-entry/src/main/resources/META-INF/services/org.pitest.mutationtest.config.ConfigurationUpdater, pitest-entry/src/test/java/org/pitest/mutationtest/autoconfig/KeepMacOsFocusTest.java, pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java
New ConfigurationUpdater interface allows this to be handled as a
feature and disabled by passed features="-macos_focus"
=> Allow supression of auto add of headless=true

README.md, pitest-entry/src/main/java/org/pitest/mutationtest/autoconfig/AutoSetThreads.java, pitest-entry/src/main/resources/META-INF/services/org.pitest.mutationtest.config.ConfigurationUpdater, pitest-entry/src/test/java/org/pitest/mutationtest/autoconfig/AutoSetThreadsTest.java
Adds the option to guess the appropriate number of threads for the current machine by adding `+auto_threads`
the features string. This option is disabled by default and designed for local use. It is not recommended
for use on a CI server.
=> guess best number of threads

pitest/src/main/java/org/pitest/coverage/execute/CoverageMinion.java, pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestMinion.java
Very occasionally the coverage process hangs while trying to read from
the communication socket. The root cause of this is not known, but
timing out is preferable to an infinite process hang.
Ten second timeout time is arbitary, picked to be unlikely to trigger
under normal circumstances. Set higher for mutation test minion as box
might be heavily loaded.
=> Set timeout for socket reads

README.md, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/equivalent/EmptyReturnsFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/equivalent/EquivalentReturnMutationFilter.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/equivalent/EquivalentReturnMutationFilterTest.java
Filter equivalent return values consistently, analysing a class no more than once for each analysis type, regardless of the number of mutants.
All types of empty value are now checked for both direct and indirect return.
=> Improve filtering of equivalent return mutants

README.md, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/staticinitializers/StaticInitializerInterceptor.java, pitest-entry/src/test/java/com/example/staticinitializers/BrokenChain.java, pitest-entry/src/test/java/com/example/staticinitializers/MethodsCallsEachOtherInLoop.java, pitest-entry/src/test/java/com/example/staticinitializers/SecondLevelPrivateMethods.java, pitest-entry/src/test/java/com/example/staticinitializers/SingletonWithWorkInInitializer.java, pitest-entry/src/test/java/com/example/staticinitializers/ThirdLevelPrivateMethods.java, pitest-entry/src/test/java/org/pitest/mutationtest/MutationCoverageReportSystemTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/staticinitializers/StaticInitializerInterceptorTest.java
Expands the analysis to catch any mutants in methods in a call tree from
the static initializer, which consists only of other private methods.
=> expand filtering of static initializer mutants

pitest-entry/src/main/java/org/pitest/mutationtest/tooling/MutationCoverage.java, pitest/src/main/java/org/pitest/coverage/execute/CoverageMinion.java, pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestWorker.java
This change is betting on that nobody is parsing the log output verbatim for further consumption.
=> Fix inconsistent spacing in logging

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigOption.java, pitest-maven-verification/src/test/resources/pit-158-coverage/pom.xml, pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/main/java/org/pitest/maven/report/PitReportMojo.java
The vast majority of users disable timestamped reports. Defaulting the parameter to true no longer makes sense.
=> Do not produce timestamped reports by default

pitest-entry/src/main/java/org/pitest/mutationtest/tooling/DirectorySourceLocator.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/SmartSourceLocator.java, pitest-entry/src/test/java/org/pitest/mutationtest/tooling/DirectorySourceLocatorTest.java
Kotlin may place files anywhere in the source tree, so need to also search outside of packages.
=> search for source outside of package dirs

pitest-entry/src/main/java/org/pitest/mutationtest/verify/DefaultBuildVerifier.java, pitest-entry/src/test/java/org/pitest/mutationtest/verify/DefaultBuildVerifierTest.java
The purpose of the check is to alert users that they must configure the compiler to include source file debug info.
Previously all classes were checked to ensure the source file was present, however it appears there may be some scenarios in which the source file is omitted when compiling kotlin.
To allow analysis of the remaining classes, the check has been relaxed so that the info must be present in at least one file, rather than all files.
=> Relax source file attribute check

pitest/src/main/java/org/pitest/coverage/execute/CoverageMinion.java
The origin log output is like "100Executing 100 tests not run during discovery", and now the useless number at the very beginning is removed.
=> Fix log output

README.md, pitest-ant/src/main/java/org/pitest/ant/PitestTask.java, pitest-ant/src/test/java/org/pitest/ant/PitestTaskTest.java, pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ConfigOption.java
The excludedRunners parameter added by #283 was only made available for the maven plugin. This change adds the parameter to the commandline interface and other build tools.
=> make excludedRunners parameter available via commandline and Ant.

README.md, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/experimental/RemoveSwitchMutator.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/experimental/RemoveSwitchMutatorTest.java, pitest/src/test/java/org/pitest/verifier/mutants/MutatorVerifier.java
Supress equivalent fall through mutants for #1137
=> do not mutate fall through switch cases

pitest-entry/src/main/java/org/pitest/mutationtest/statistics/Score.java, pitest/src/main/java/org/pitest/util/Log.java
The `toString()` method is not needed in cases the underlying method handles the conversion. Also calling toString() on a String is redundant. Removing them simplifies the code.
* UnnecessaryToStringCall (3)
=> refactor: refactor bad smell UnnecessaryToStringCall 

README.md, pitest/src/main/java/org/pitest/classinfo/SyntheticMethodFilter.java, pitest/src/main/java/org/pitest/coverage/CoverageClassVisitor.java, pitest/src/test/java/org/pitest/coverage/CoverageTransformerTest.java
Coverage was being generated for synthetic methods, artificially inflating the number of covered lines for some kotlin classes. This change prevents probes from being inserting into them, duplicating the logic use elsewhere to ensure that lambda implementations still have probes, despite their synthetic flag.
=> Avoid instrumenting synthetic methods

pitest-entry/src/main/java/org/pitest/mutationtest/tooling/MutationCoverage.java, pitest-entry/src/test/java/org/pitest/mutationtest/tooling/MutationCoverageReportTest.java
Every line within a project was being treated as a codeline, resulting in very low coverage stats on the commandline when filters were applied.
=> report only target code lines

pitest-entry/src/test/java/org/pitest/coverage/CoverageTransformerTest.java, pitest/src/main/java/org/pitest/classinfo/MethodFilteringAdapter.java, pitest/src/main/java/org/pitest/coverage/CoverageClassVisitor.java, pitest/src/test/java/org/pitest/coverage/CoverageTransformerTest.java
Occured with Kotlin 1.4 for some language constructs.
=> avoid creating duplicate clinit when existing one is synthetic

pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java, pitest-maven/src/test/java/org/pitest/maven/PitMojoTest.java
The jetbrains kotlin plugin doesn't seem to use the source dirs configured in the maven model. Many projects will therefore not have them properly configured. This hack ensures pitest picks them up if they are present.
=> Auto add kotlin source dirs when present

pitest/src/main/java/org/pitest/plugin/FeatureSelector.java, pitest/src/test/java/org/pitest/plugin/FeatureSelectorTest.java
Configuring an on by default feature caused a 2nd instance to be created.
=> Prevent double instantiation of features

pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/ForEachLoopFilter.java
Hack to avoid nfa degraded performance when large methods were present as it prevented use of the cache.
=> improve for each filter performance

pitest/src/main/java/org/pitest/plugin/Feature.java, pitest/src/main/java/org/pitest/plugin/FeatureSelector.java, pitest/src/test/java/org/pitest/plugin/FeatureSelectorTest.java, pitest/src/test/java/org/pitest/plugin/FeatureTest.java
=> make order features applied in consistent

pitest-entry/src/main/java/org/pitest/mutationtest/report/csv/CSVReportListener.java, pitest-entry/src/test/java/org/pitest/mutationtest/report/csv/CSVReportListenerTest.java
This is a possible solution for #1178.  
It quotes the `killingTest` before writing to CSV report.
Fixes #1178
=> fix: quote killingTest in CSV report

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java
The gradle plugin uses a classpath file to communicate with pitest when the user classpath is too large to pass on the commandline line. In this scenario the same issue is highly likely to be encountered when pitest launches processes.
This change auto sets the classpath jar flag when a classpath file is supplied to avoid the user having to set two parameters.
=> use classpath jar when classpath file provided

pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/RegionInterceptor.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/ForEachLoopFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/InlinedFinallyBlockFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/timeout/AvoidForLoopCounterFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/timeout/InfiniteLoopFilter.java, pitest/src/main/java/org/pitest/bytecode/ASMVersion.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/AnnotationInfo.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/BasicContext.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/FieldInfo.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/MethodInfo.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/MethodMutatorFactory.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/MutatingClassVisitor.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/MutationContext.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/NoMethodContext.java
Introduces extensions points to make field mutation possible via third party plugins. Doing so remains challenging due to the need to understand and hook into the frameworks that read the modified annotations.
=> Enable annotation mutations

pitest-aggregator/src/main/java/org/pitest/aggregate/ReportAggregator.java, pitest-aggregator/src/test/java/org/pitest/aggregate/ReportAggregatorBuilderTest.java
Similar to #466, when using the gradle-pitest-plugin it is possible to end up in a scenario where `linecoverage.xml` and `mutations.xml` file paths are sent to the `ReportAggregatorBuilder` but they do not actually exist.
An example of this would be where you have a multi module project with some nested sub modules:
```
sub-module/
nested-module-a/
src/
main/
...
test/
...
build.gradle
nested-module-b/
src/
main/
...
test/
...
build.gradle
build.gradle
```
The sub-module does not have a build.gradle, code, or tests, yet the plugin passes the file paths to the builder as if they did exist.
I am proposing that the ReportAggregatorBuilder could log the missing files instead of raising an error. This would allow the aggregation to continue in cases such as the above, but still inform users of …
=> feat: ignore absent ReportAggregatorBuilder files

pitest/src/main/java/org/pitest/util/Glob.java, pitest/src/test/java/org/pitest/util/GlobTest.java
Fixes #1144
Currently it is not possible to write a glob that matches zero or more packages. This PR introduces the well-kown doube-star matcher to enable this:
`**.databinding.**.Foo` 
* matches `databinding.Foo`
* matches `foo.car.databinding.bar.Foo`
* NOT matches `databindingfoo.Foo`
=> Support glob pattern **. to match zero or more packages

pitest/src/main/java/org/pitest/coverage/execute/CoverageTestExecutionListener.java
=> Make the coverage test execution listener thread-safe

pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/main/java/org/pitest/maven/PitMojo.java, pitest-maven/src/main/java/org/pitest/maven/ScmMojo.java, pitest-maven/src/test/java/org/pitest/maven/BasePitMojoTest.java, pitest-maven/src/test/java/org/pitest/maven/ScmMojoTest.java
The pitest minions require a version of the junit-platform-launcher which matches the version of junit 5 used by the SUT. Previously this was provided by the cludge of shading it into the junit5 plugin, but this causes constant headaches with version mismatched.
This change pulls in a matching version of platform-launcher in the same manner that surefire does. It also allows junit dependencies to be explicitly included pitest config should this resolution give the wrong results.
=> Auto add junit-platform-launcher to classpath

pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/MutatorSpecificInterceptor.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/RegionInterceptor.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/equivalent/DivisionByMinusOneFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/equivalent/DivisionByMinusOneFilterFactory.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/equivalent/EmptyReturnsFilter.java, pitest-entry/src/main/resources/META-INF/services/org.pitest.mutationtest.build.MutationInterceptorFactory, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/equivalent/DivisionByMinusOneFilterFactoryTest.java
Filter out equivalent mutants of the form
(a + b) * -1 -> (a + b) / -1
Does not filter the opposite as, although it is also equivalent, there is no good reason to express conversion to a negative as a division operation over the more common multiplication.
=> filter equivalent divide by minus one mutants

pitest-entry/src/main/java/org/pitest/coverage/CoverageSummary.java, pitest-entry/src/main/java/org/pitest/mutationtest/statistics/MutationStatistics.java, pitest-entry/src/main/java/org/pitest/mutationtest/statistics/Score.java, pitest-entry/src/main/java/org/pitest/util/PercentageCalculator.java, pitest-entry/src/test/java/org/pitest/util/PercentageCalculatorTest.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationTotals.java, pitest-html-report/src/test/java/org/pitest/mutationtest/report/html/MutationTotalsTest.java
Fixes #375
Supersedes #776
With this PR hopefully all percentage calculation uses the common logic introcuded in #638.
This should avoid everywhere showing 100% if not the full total is reached.
As a positive side-effect it also fixes a potential arithmetic exception in `getTestStrength()`
as it was not the divisor that was checked for zero to avoid it, probably by bad copy & paste.
=> Use unified percentage calculation logic

pitest/src/main/java/org/pitest/mutationtest/engine/gregor/MethodMutatorFactory.java, pitest/src/main/java/org/pitest/mutationtest/engine/gregor/mutators/InlineConstantMutator.java, pitest/src/test/java/org/pitest/verifier/mutants/MutatorVerifierStart.java, pitest/src/test/java/org/pitest/verifier/mutants/ScanningClassVisitor.java
Add in assertion for all tests using verifier to ensure bytecode remains unaltered.
Fix applied to InlineConstantMutator which produced functionally equivalent but different bytecode.
=> Ensure mutators do not modify bytecode during scan stage

pitest-entry/src/main/java/org/pitest/mutationtest/build/MutationTestBuilder.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/MutationTestUnit.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/MutationTestUnitTest.java
Test classes to be sent to the minion are now calculated from the list of remaning mutations. In the event of a timeout, this list may be shorter than the initial list, and the scanning of the test classes within the minion thereby avoided.
=> delay test class identification

pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/test/java/org/pitest/maven/PitMojoTest.java
Additional parameter extraFeatures allowed features to be added from the commandline without overwriting/needing to respecify features set within the pom.xml
=> extra features param for maven

pitest-aggregator/src/main/java/org/pitest/aggregate/ReportAggregator.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-entry/src/main/java/org/pitest/mutationtest/report/xml/XMLReportFactory.java, pitest-entry/src/main/java/org/pitest/mutationtest/report/xml/XMLReportListener.java, pitest-entry/src/test/java/org/pitest/mutationtest/report/xml/XMLReportListenerTest.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/AnnotatedLineFactory.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/HtmlReportFactory.java, pitest-html-report/src/main/java/org/pitest/mutationtest/report/html/MutationHtmlReportListener.java, pitest-html-report/src/main/resources/templates/mutation/mutation_package_index.st, pitest-html-report/src/main/resources/templates/mutation/package_index.st, pitest-html-report/src/test/java/org/pitest/mutationtest/report/html/MutationHtmlReportListenerTest.java, pitest-maven/src/main/java/org/pitest/maven/report/AbstractPitAggregationReportMojo.java
Arcmutates advanced incremental processing includes the option to avoid gathering coverage for tests which cannot kill an in scope mutant. Although this speeds up processing the html report shows most lines as uncovered when this feature is activated. Reporting of line coverage it therefore disabled when this feature is activated.
=> suppress reporting of coverage stats

pitest-maven-verification/src/test/resources/pit-quarkus/pom.xml, pitest-maven-verification/src/test/resources/pit-quarkus/src/main/java/com/example/GreetingResource.java, pitest-maven-verification/src/test/resources/pit-quarkus/src/main/java/com/example/controller/ExampleController.java, pitest-maven-verification/src/test/resources/pit-quarkus/src/main/java/com/example/service/ExampleService.java, pitest-maven-verification/src/test/resources/pit-quarkus/src/test/java/com/example/ExampleControllerTest.java, pitest-maven-verification/src/test/resources/pit-quarkus/src/test/java/com/example/ExampleServiceTest.java, pitest-maven-verification/src/test/resources/pit-quarkus/src/test/java/com/example/GreetingResourceTest.java
- Bump Quarkus from 2.8 to 3.4
- Add usual Quarkus test from generated application (https://code.quarkus.io/ for example)
Update of test coverage added in https://github.com/hcoles/pitest/pull/1022
Checks:
Executed `mvn clean test org.pitest:pitest-maven:mutationCoverage -Dpit.version=1.15.1` from `pitest-maven-verification/src/test/resources/pit-quarkus` directory
Also executed `mvn clean verify -Dit.test=PitMojoIT#shouldWorkWithQuarkus` from `pitest-maven-verification`
=>  Bump Quarkus from 2.8 to 3.4 and add usual Quarkus test from generated application 

pitest-entry/src/main/java/org/pitest/coverage/CompoundCoverageExporterFactory.java, pitest-entry/src/main/java/org/pitest/coverage/CoverageExporterFactory.java, pitest-entry/src/main/java/org/pitest/coverage/DefaultCoverageExporterFactory.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/PluginServices.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/SettingsFactory.java, pitest-entry/src/main/resources/META-INF/services/org.pitest.coverage.CoverageExporterFactory, pitest-entry/src/test/java/org/pitest/mutationtest/config/SettingsFactoryTest.java, pitest-entry/src/test/java/org/pitest/process/ArgLineParserTest.java
Additional coverage exporters can now be used.
Exporting coverage is still controlled by the `exportLineCoverage` parameter, but additional exporters can be provided by plugins and enabled/disabled using feature strings.
To disable the default exporter pass `-defaultCoverage` as a feature string.
=> Pluggable coverage

pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/staticinitializers/StaticInitializerInterceptor.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/staticinitializers/StaticInitializerInterceptorTest.java
Temporarily #1274 until additional logic added to handle increased likelihood of filtering mutants to delayed execution code reported in #1291 is implemented.
=> temporarily remove dynamic call tracking

pitest/src/main/java/org/pitest/coverage/execute/CoverageOptions.java, pitest/src/test/java/org/pitest/coverage/execute/CoverageOptionsTest.java
If code was packaged anywhere in com.sun* it was being picked up by the filter for legacy jdk classes in the com.sun.* package.
=> Non jdk classes picked up by filter

pitest-maven-verification/src/test/java/org/pitest/PitMojoIT.java, pitest-maven-verification/src/test/resources/pit-surefire-excludes/pom.xml, pitest-maven-verification/src/test/resources/pit-surefire-excludes/src/test/java/com/example/AnotherTest.java, pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/main/java/org/pitest/maven/ScmMojo.java, pitest-maven/src/main/java/org/pitest/maven/SurefireConfigConverter.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java, pitest-maven/src/test/java/org/pitest/maven/SurefireConfigConverterTest.java
In the last release pitest was updated to read argLine arguments from the surefire config, including support for surefire's late parsing of fields using the '@' symbol.
Unfortunately standard fields using the maven '$' syntax were being brought through unreplaced when read from surefire, causing errors when launching processes.
This change resolves this issues, and also moves the parsing of surefire arglines under the control of a new `parseSurefireArgLine` parameter. This is enabled by default, but can be set to false if attempting to read the surefire argline causes an issue for a particular project.
=> replace standard maven properties imported from surefire

pitest-entry/src/main/java/org/pitest/bytecode/analysis/InstructionMatchers.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/defensive/ReturnUnmodifiableCollection.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/defensive/ReturnUnmodifiableCollectionFactory.java, pitest-entry/src/main/resources/META-INF/services/org.pitest.mutationtest.build.MutationInterceptorFactory, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/defensive/ReturnUnmodifiableCollectionFactoryTest.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/equivalent/EqualsPerformanceShortcutFilterTest.java, pitest/src/main/java/org/pitest/util/StreamUtil.java
It's common practice in some teams to wrap mutable collections with unmodifiable wrappers before returning them from a class to prevent accidental modification of state.
```java
class Foo {
private final List<String> field;
...
List<String> doStuff() {
return Collections.unmodifiableList(field);
}
}
```
Although the presence of the wrapper can be easily detected by a test that attempts to modify the state of the list, some teams do not wish to specify this behaviour.
This change provides the option to filter out mutations implementing this defensive coding pattern.
The filter is disabled by default, but can be enabled with the `+funmodifiablecollection` feature string.
=> filter mutations to defensive unmodifiable collection returns

pitest-aggregator/pom.xml, pitest-maven/src/main/java/org/pitest/maven/report/AbstractPitAggregationReportMojo.java, pom.xml
Version mismatches between jackson used on plugins can cause errors, so we are forced to shade it.
=> shade jackson

pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java
Right now, the history file locations are logged only when the `withHistory` option is enabled.  If they are set explicitly, the locations are not logged.
Logging the history file locations even when set explicitly can make the developer's life easy when integrated into a CI/Nightly build server.  They know exactly which file to archive between builds.  
This also saves time for the developer when debugging the history storage file config for the CI/Nightly build server.
=> log the history file locations when set explicitly

pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java
When both withHistory and explicit history paths are set, the log message is misleading.
This change ensures that withHistory overrides explicit paths and the correct file path is logged.
=> fix misleading path logging of history files

pitest-maven-verification/src/test/resources/pit-kotlin-multi-module/sub-module-1/pom.xml, pitest-maven-verification/src/test/resources/pit-kotlin-multi-module/sub-module-2/pom.xml, pitest-maven-verification/src/test/resources/pit-kotlin-multi-module/sub-module-3/pom.xml, pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java, pitest-maven/src/test/java/org/pitest/maven/PitMojoTest.java
src/main/kotlin and src/test/kotlin are now auto added to the a maven project by the mojo if present.
This is necessary as, for maven builds, these directories are often added at runtime by the build helper or kotlin plugins. If they pitest goal is run directly (as is common) these plugins will not fire and the config will be missing causing confusing failures.
This replaces an earlier hack where there directories were aded at a lower level.
=> Auto add standard kotlin source dirs if present

pitest/src/main/java/org/pitest/coverage/execute/CoverageMinion.java, pitest/src/main/java/org/pitest/mutationtest/environment/TransformationPlugin.java, pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestMinion.java, pitest/src/main/java/org/pitest/mutationtest/execute/MutationTestWorker.java, pitest/src/main/java/org/pitest/mutationtest/mocksupport/JavassistInputStreamInterceptorAdapter.java, pitest/src/main/java/org/pitest/mutationtest/mocksupport/JavassistInterceptor.java, pitest/src/main/java/org/pitest/mutationtest/mocksupport/JavassistTransformation.java, pitest/src/main/java/org/pitest/mutationtest/mocksupport/ResetJavassistEnvironment.java, pitest/src/main/resources/META-INF/services/org.pitest.mutationtest.environment.EnvironmentResetPlugin, pitest/src/main/resources/META-INF/services/org.pitest.mutationtest.environment.TransformationPlugin, pitest/src/test/java/org/pitest/mutationtest/mocksupport/BendJavassistToMyWillTransformerTest.java, pitest/src/test/java/org/pitest/mutationtest/mocksupport/JavassistInputStreamInterceptorAdapterTest.java
Extends the transformation plugin interface to allow separate transformations at the coverage and mutation testing phases.
Javassist implementation is moved into plugin using the new interface.
=> Extend transformation extension point

pitest-entry/pom.xml, pitest-maven/src/main/java/org/pitest/maven/report/generator/ReportGenerationContext.java
The reflection based toString generator fails on some modern jvms as apache commons tries to parse out the version of Java, but fails due to outdated assumptions.
Not clear why it's inmportant to have a toString method here, but replacing with an autogenerated one should solve #1358. Implementation excludes logger and sink form toString as it's unclear how they would be useful.
=> remove use of reflection based toString generator

pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/annotations/ExcludedAnnotationInterceptor.java, pitest-entry/src/test/java/org/pitest/mutationtest/build/intercept/annotations/ExcludedAnnotationInterceptorTest.java
This PR fixes the problem described [1]. 
[1] - https://github.com/hcoles/pitest/issues/1360
=> Mutation coverage fix within lambdas 

pitest-maven/src/main/java/org/pitest/maven/AbstractPitMojo.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/test/java/org/pitest/maven/BasePitMojoTest.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java
Added a lookup of `Settings#getLocalRepository()` to the expansion of variables referenced within `<argLine>`  elements.
fixes hcoles/pitest#1333
=> fixes hcoles/pitest#1333 Expand ${settings.localRepository} in <argLine>

pitest-aggregator/src/main/java/org/pitest/aggregate/ReportAggregator.java, pitest-entry/src/main/java/org/pitest/coverage/CoverageData.java, pitest-entry/src/main/java/org/pitest/coverage/CoverageDatabase.java, pitest-entry/src/main/java/org/pitest/coverage/CoverageSummary.java, pitest-entry/src/main/java/org/pitest/coverage/NoCoverage.java, pitest-entry/src/main/java/org/pitest/coverage/execute/DefaultCoverageGenerator.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/MutationCoverage.java, pitest-entry/src/test/java/org/pitest/coverage/CoverageDataTest.java, pitest-entry/src/test/java/org/pitest/coverage/CoverageSummaryTest.java, pitest-maven/src/test/java/org/pitest/maven/PitMojoTest.java
Report number of examined tests on console. Of some interest to end users, but reporting in a structured way via the AnalysisResult is mainly of use for tests. Making the number of internally examined tests available externally allows tests to ensure that optimisation measures are working.
=> report test count

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/OptionsParser.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/coverage/execute/CoverageProcess.java, pitest-entry/src/main/java/org/pitest/mutationtest/config/ReportOptions.java, pitest-entry/src/main/java/org/pitest/mutationtest/execute/MutationTestProcess.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/EntryPoint.java, pitest-entry/src/main/java/org/pitest/process/Java9Process.java, pitest-entry/src/main/java/org/pitest/process/LaunchOptions.java, pitest-entry/src/main/java/org/pitest/process/ProcessArgs.java, pitest-entry/src/main/java/org/pitest/process/WrappingProcess.java, pitest-entry/src/test/java/org/pitest/process/WrappingProcessTest.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/main/java/org/pitest/maven/PitMojo.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java
Since Java 9 it has been possible to pass parameters to Java processes via a file. This cleanly solves the issue of parameter length limits on all platforms.
Previously, if the user encountered errors due to a large classpath, they could enable a flag so that a  jar file was  constructed with a manifest containing the classpath. This functionality can now be replaced as the minimum supported version has been raised to 11.
The parameter file is a more flexible general solution which will continue to work if/when pitest adds support for module paths.
=> Pass process parameters by file

pitest-command-line/src/main/java/org/pitest/mutationtest/commandline/ParseResult.java, pitest-command-line/src/test/java/org/pitest/mutationtest/commandline/OptionsParserTest.java, pitest-entry/src/main/java/org/pitest/classinfo/ClassInfo.java, pitest-entry/src/main/java/org/pitest/coverage/execute/CoverageProcess.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/RegionInterceptor.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/annotations/ExcludedAnnotationInterceptor.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/ForEachLoopFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/InlinedFinallyBlockFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/timeout/AvoidForLoopCounterFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/timeout/InfiniteLoopFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/execute/MutationTestProcess.java, pitest-entry/src/main/java/org/pitest/mutationtest/incremental/IncrementalAnalyser.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/EntryPoint.java, pitest-entry/src/main/java/org/pitest/mutationtest/tooling/JarCreatingJarFinder.java, pitest-entry/src/main/java/org/pitest/util/FileUtil.java, pitest-entry/src/test/java/org/pitest/mutationtest/incremental/IncrementalAnalyserTest.java, pitest-maven/src/main/java/org/pitest/maven/MojoToReportOptionsConverter.java, pitest-maven/src/test/java/org/pitest/maven/MojoToReportOptionsConverterTest.java, pitest/src/main/java/org/pitest/classinfo/ComputeClassWriter.java, pitest/src/main/java/org/pitest/mutationtest/config/PrioritisingTestConfiguration.java, pitest/src/test/java/org/pitest/mutationtest/engine/gregor/mutators/ConstructorCallMutatorTest.java
This PR adopts features from Java 11, following
- https://github.com/hcoles/pitest/issues/1328
- https://github.com/hcoles/pitest/pull/1380
Created using https://docs.openrewrite.org/recipes/java/migrate/java8tojava11
=> Adopt features from Java 11

pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/equivalent/EqualsPerformanceShortcutFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/javafeatures/ForEachLoopFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/timeout/AvoidForLoopCounterFilter.java, pitest-entry/src/main/java/org/pitest/mutationtest/build/intercept/timeout/InfiniteLoopFilter.java
It appears to be possible for the pitest filters to be passed methods without instructions. It is not yet clear how this situation arises, so this change adds logging along with a check.
=> catch and log empty methods
